name: CanHasWebsite
favicon: null
layout_spectrum: 0.18671793956309557
typography_spectrum: 0.8274809289723635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.43166347057558596
purpose:
  - name: follow
    item: null
    url: null
